-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwopple.com/zwoptex/)
--
-- For more details, see http://blog.anscamobile.com/2012/03/image-sheets-image-groups-and-sprites/

local sheet =
{
	frames = {
		
		{ x = 484, y = 1077, width = 30, height = 40 }, -- 0.png
		
		{ x = 484, y = 995, width = 30, height = 40 }, -- 1.png
		
		{ x = 484, y = 954, width = 30, height = 40 }, -- 2.png
		
		{ x = 515, y = 1022, width = 30, height = 40 }, -- 3.png
		
		{ x = 515, y = 1063, width = 30, height = 40 }, -- 4.png
		
		{ x = 515, y = 981, width = 30, height = 40 }, -- 5.png
		
		{ x = 815, y = 1192, width = 30, height = 40 }, -- 6.png
		
		{ x = 484, y = 1036, width = 30, height = 40 }, -- 7.png
		
		{ x = 515, y = 1104, width = 30, height = 40 }, -- 8.png
		
		{ x = 815, y = 1233, width = 30, height = 40 }, -- 9.png
		
		{ x = 995, y = 345, width = 8, height = 90 }, -- barrier_01.png
		
		{ x = 1015, y = 289, width = 8, height = 90 }, -- barrier_02.png
		
		{ x = 986, y = 345, width = 8, height = 90 }, -- barrier_03.png
		
		{ x = 522, y = 849, width = 30, height = 43 }, -- blue_0.png
		
		{ x = 860, y = 1087, width = 30, height = 43 }, -- blue_1.png
		
		{ x = 890, y = 1138, width = 30, height = 43 }, -- blue_2.png
		
		{ x = 891, y = 1094, width = 30, height = 43 }, -- blue_3.png
		
		{ x = 522, y = 805, width = 30, height = 43 }, -- blue_4.png
		
		{ x = 860, y = 1130, width = 30, height = 43 }, -- blue_5.png
		
		{ x = 882, y = 735, width = 30, height = 43 }, -- blue_6.png
		
		{ x = 860, y = 1174, width = 30, height = 43 }, -- blue_7.png
		
		{ x = 522, y = 761, width = 30, height = 43 }, -- blue_8.png
		
		{ x = 882, y = 779, width = 30, height = 43 }, -- blue_9.png
		
		{ x = 727, y = 928, width = 132, height = 132 }, -- chicken_body.png
		
		{ x = 0, y = 449, width = 380, height = 376 }, -- chicken_corner.png
		
		{ x = 944, y = 756, width = 74, height = 74 }, -- chicken_head.png
		
		{ x = 920, y = 1147, width = 80, height = 80 }, -- constructor.png
		
		{ x = 167, y = 1227, width = 130, height = 83 }, -- crash00.png
		
		{ x = 131, y = 1396, width = 130, height = 83 }, -- crash01.png
		
		{ x = 0, y = 1353, width = 130, height = 83 }, -- crash02.png
		
		{ x = 666, y = 1339, width = 130, height = 83 }, -- crash03.png
		
		{ x = 167, y = 1311, width = 130, height = 83 }, -- crash04.png
		
		{ x = 298, y = 1332, width = 130, height = 83 }, -- crash05.png
		
		{ x = 944, y = 831, width = 74, height = 72 }, -- egg.png
		
		{ x = 769, y = 0, width = 248, height = 288 }, -- egg_stars.png
		
		{ x = 944, y = 904, width = 74, height = 72 }, -- egg_strong.png
		
		{ x = 846, y = 1217, width = 67, height = 76 }, -- golden_egg.png
		
		{ x = 0, y = 0, width = 768, height = 448 }, -- grass.png
		
		{ x = 481, y = 1636, width = 482, height = 186 }, -- help1.png
		
		{ x = 262, y = 1423, width = 434, height = 212 }, -- help2.png
		
		{ x = 481, y = 1823, width = 416, height = 178 }, -- help3.png
		
		{ x = 0, y = 1636, width = 480, height = 190 }, -- help4.png
		
		{ x = 0, y = 1438, width = 124, height = 58 }, -- level.png
		
		{ x = 967, y = 707, width = 48, height = 48 }, -- lock_01.png
		
		{ x = 209, y = 957, width = 111, height = 146 }, -- menu.png
		
		{ x = 649, y = 634, width = 91, height = 91 }, -- menu_popup.png
		
		{ x = 0, y = 1266, width = 166, height = 86 }, -- next_txt.png
		
		{ x = 546, y = 1094, width = 80, height = 80 }, -- pause.png
		
		{ x = 381, y = 449, width = 290, height = 130 }, -- pipe.png
		
		{ x = 969, y = 656, width = 50, height = 50 }, -- pipe_g.png
		
		{ x = 918, y = 642, width = 50, height = 50 }, -- pipe_r.png
		
		{ x = 753, y = 506, width = 164, height = 228 }, -- plate_hs.png
		
		{ x = 546, y = 1013, width = 80, height = 80 }, -- play.png
		
		{ x = 332, y = 1219, width = 112, height = 112 }, -- play_popup.png
		
		{ x = 0, y = 1179, width = 166, height = 86 }, -- play_txt.png
		
		{ x = 918, y = 575, width = 66, height = 66 }, -- powerup_strong.png
		
		{ x = 372, y = 954, width = 111, height = 151 }, -- repeat.png
		
		{ x = 627, y = 1078, width = 80, height = 80 }, -- restart.png
		
		{ x = 332, y = 1106, width = 112, height = 112 }, -- restart_popup.png
		
		{ x = 649, y = 726, width = 91, height = 91 }, -- restart_popup_small.png
		
		{ x = 553, y = 926, width = 86, height = 86 }, -- rock.png
		
		{ x = 241, y = 826, width = 130, height = 130 }, -- rock_s.png
		
		{ x = 702, y = 1192, width = 111, height = 146 }, -- sound_off.png
		
		{ x = 885, y = 1298, width = 111, height = 146 }, -- sound_on.png
		
		{ x = 627, y = 1159, width = 74, height = 71 }, -- star.png
		
		{ x = 445, y = 1262, width = 220, height = 94 }, -- start.png
		
		{ x = 562, y = 580, width = 86, height = 171 }, -- straw.png
		
		{ x = 445, y = 1175, width = 171, height = 86 }, -- straw_.png
		
		{ x = 0, y = 939, width = 208, height = 126 }, -- straw__s.png
		
		{ x = 741, y = 735, width = 140, height = 192 }, -- straw_s.png
		
		{ x = 381, y = 761, width = 140, height = 192 }, -- straw_s.psd
		
		{ x = 649, y = 819, width = 88, height = 86 }, -- straw_small.png
		
		{ x = 725, y = 1061, width = 134, height = 130 }, -- straw_small_s.png
		
		{ x = 640, y = 993, width = 84, height = 84 }, -- switch.png
		
		{ x = 922, y = 1062, width = 84, height = 84 }, -- switch_auto.png
		
		{ x = 562, y = 752, width = 86, height = 86 }, -- switch_auto_top.png
		
		{ x = 922, y = 977, width = 84, height = 84 }, -- switch_freez.png
		
		{ x = 381, y = 580, width = 180, height = 180 }, -- switch_freez_grass.png
		
		{ x = 640, y = 906, width = 86, height = 86 }, -- switch_freez_top.png
		
		{ x = 209, y = 1104, width = 122, height = 122 }, -- switch_s.png
		
		{ x = 553, y = 839, width = 86, height = 86 }, -- switch_top.png
		
		{ x = 429, y = 1357, width = 128, height = 52 }, -- turns.png
		
		{ x = 672, y = 449, width = 80, height = 184 }, -- tutorial_arrow.png
		
		{ x = 769, y = 289, width = 216, height = 216 }, -- tutorial_ring.png
		
		{ x = 0, y = 826, width = 240, height = 112 }, -- tutorial_tap_to_rotate.png
		
		{ x = 0, y = 1066, width = 208, height = 112 }, -- tutorial_tap_to_start.png
		
		{ x = 918, y = 693, width = 48, height = 48 }, -- unlock_01.png
		
		{ x = 986, y = 289, width = 28, height = 55 }, -- white_#.png
		
		{ x = 891, y = 1006, width = 30, height = 43 }, -- white_0.png
		
		{ x = 913, y = 742, width = 30, height = 43 }, -- white_1.png
		
		{ x = 913, y = 786, width = 30, height = 43 }, -- white_2.png
		
		{ x = 891, y = 962, width = 30, height = 43 }, -- white_3.png
		
		{ x = 913, y = 830, width = 30, height = 43 }, -- white_4.png
		
		{ x = 860, y = 1043, width = 30, height = 43 }, -- white_5.png
		
		{ x = 882, y = 911, width = 30, height = 43 }, -- white_6.png
		
		{ x = 522, y = 893, width = 30, height = 43 }, -- white_7.png
		
		{ x = 985, y = 612, width = 30, height = 43 }, -- white_8.png
		
		{ x = 860, y = 999, width = 30, height = 43 }, -- white_9.png
		
		{ x = 985, y = 568, width = 30, height = 43 }, -- white_x.png
		
		{ x = 918, y = 506, width = 66, height = 68 }, -- x1.png
		
		{ x = 815, y = 1294, width = 70, height = 68 }, -- x2.png
		
		{ x = 915, y = 1228, width = 70, height = 68 }, -- x3.png
		
		{ x = 882, y = 867, width = 30, height = 43 }, -- yellow_0.png
		
		{ x = 860, y = 955, width = 30, height = 43 }, -- yellow_1.png
		
		{ x = 986, y = 436, width = 30, height = 43 }, -- yellow_2.png
		
		{ x = 913, y = 918, width = 30, height = 43 }, -- yellow_3.png
		
		{ x = 913, y = 874, width = 30, height = 43 }, -- yellow_4.png
		
		{ x = 882, y = 823, width = 30, height = 43 }, -- yellow_5.png
		
		{ x = 986, y = 480, width = 30, height = 43 }, -- yellow_6.png
		
		{ x = 985, y = 524, width = 30, height = 43 }, -- yellow_7.png
		
		{ x = 522, y = 937, width = 30, height = 43 }, -- yellow_8.png
		
		{ x = 891, y = 1050, width = 30, height = 43 }, -- yellow_9.png
		
	},

	sheetContentWidth = 1024,
	sheetContentHeight = 2048,

	frameIndex =
	{
		
		["0.png"] = 1,
		
		["1.png"] = 2,
		
		["2.png"] = 3,
		
		["3.png"] = 4,
		
		["4.png"] = 5,
		
		["5.png"] = 6,
		
		["6.png"] = 7,
		
		["7.png"] = 8,
		
		["8.png"] = 9,
		
		["9.png"] = 10,
		
		["barrier_01.png"] = 11,
		
		["barrier_02.png"] = 12,
		
		["barrier_03.png"] = 13,
		
		["blue_0.png"] = 14,
		
		["blue_1.png"] = 15,
		
		["blue_2.png"] = 16,
		
		["blue_3.png"] = 17,
		
		["blue_4.png"] = 18,
		
		["blue_5.png"] = 19,
		
		["blue_6.png"] = 20,
		
		["blue_7.png"] = 21,
		
		["blue_8.png"] = 22,
		
		["blue_9.png"] = 23,
		
		["chicken_body.png"] = 24,
		
		["chicken_corner.png"] = 25,
		
		["chicken_head.png"] = 26,
		
		["constructor.png"] = 27,
		
		["crash00.png"] = 28,
		
		["crash01.png"] = 29,
		
		["crash02.png"] = 30,
		
		["crash03.png"] = 31,
		
		["crash04.png"] = 32,
		
		["crash05.png"] = 33,
		
		["egg.png"] = 34,
		
		["egg_stars.png"] = 35,
		
		["egg_strong.png"] = 36,
		
		["golden_egg.png"] = 37,
		
		["grass.png"] = 38,
		
		["help1.png"] = 39,
		
		["help2.png"] = 40,
		
		["help3.png"] = 41,
		
		["help4.png"] = 42,
		
		["level.png"] = 43,
		
		["lock_01.png"] = 44,
		
		["menu.png"] = 45,
		
		["menu_popup.png"] = 46,
		
		["next_txt.png"] = 47,
		
		["pause.png"] = 48,
		
		["pipe.png"] = 49,
		
		["pipe_g.png"] = 50,
		
		["pipe_r.png"] = 51,
		
		["plate_hs.png"] = 52,
		
		["play.png"] = 53,
		
		["play_popup.png"] = 54,
		
		["play_txt.png"] = 55,
		
		["powerup_strong.png"] = 56,
		
		["repeat.png"] = 57,
		
		["restart.png"] = 58,
		
		["restart_popup.png"] = 59,
		
		["restart_popup_small.png"] = 60,
		
		["rock.png"] = 61,
		
		["rock_s.png"] = 62,
		
		["sound_off.png"] = 63,
		
		["sound_on.png"] = 64,
		
		["star.png"] = 65,
		
		["start.png"] = 66,
		
		["straw.png"] = 67,
		
		["straw_.png"] = 68,
		
		["straw__s.png"] = 69,
		
		["straw_s.png"] = 70,
		
		["straw_s.psd"] = 71,
		
		["straw_small.png"] = 72,
		
		["straw_small_s.png"] = 73,
		
		["switch.png"] = 74,
		
		["switch_auto.png"] = 75,
		
		["switch_auto_top.png"] = 76,
		
		["switch_freez.png"] = 77,
		
		["switch_freez_grass.png"] = 78,
		
		["switch_freez_top.png"] = 79,
		
		["switch_s.png"] = 80,
		
		["switch_top.png"] = 81,
		
		["turns.png"] = 82,
		
		["tutorial_arrow.png"] = 83,
		
		["tutorial_ring.png"] = 84,
		
		["tutorial_tap_to_rotate.png"] = 85,
		
		["tutorial_tap_to_start.png"] = 86,
		
		["unlock_01.png"] = 87,
		
		["white_#.png"] = 88,
		
		["white_0.png"] = 89,
		
		["white_1.png"] = 90,
		
		["white_2.png"] = 91,
		
		["white_3.png"] = 92,
		
		["white_4.png"] = 93,
		
		["white_5.png"] = 94,
		
		["white_6.png"] = 95,
		
		["white_7.png"] = 96,
		
		["white_8.png"] = 97,
		
		["white_9.png"] = 98,
		
		["white_x.png"] = 99,
		
		["x1.png"] = 100,
		
		["x2.png"] = 101,
		
		["x3.png"] = 102,
		
		["yellow_0.png"] = 103,
		
		["yellow_1.png"] = 104,
		
		["yellow_2.png"] = 105,
		
		["yellow_3.png"] = 106,
		
		["yellow_4.png"] = 107,
		
		["yellow_5.png"] = 108,
		
		["yellow_6.png"] = 109,
		
		["yellow_7.png"] = 110,
		
		["yellow_8.png"] = 111,
		
		["yellow_9.png"] = 112,
		
	}
}

return sheet