-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwopple.com/zwoptex/)
--
-- For more details, see http://blog.anscamobile.com/2012/03/image-sheets-image-groups-and-sprites/

local sheet =
{
	frames = {
		
		{ x = 0, y = 0, width = 768, height = 1363 }, -- bck.png
		
		{ x = 1684, y = 308, width = 259, height = 147 }, -- bck_chmura_01.png
		
		{ x = 1510, y = 745, width = 248, height = 139 }, -- bck_chmura_02.png
		
		{ x = 1684, y = 456, width = 256, height = 146 }, -- bck_chmura_03.png
		
		{ x = 1258, y = 745, width = 251, height = 143 }, -- bck_chmura_04.png
		
		{ x = 1296, y = 199, width = 220, height = 245 }, -- bck_jajo.png
		
		{ x = 1538, y = 0, width = 266, height = 159 }, -- bck_kamienie.png
		
		{ x = 769, y = 940, width = 458, height = 487 }, -- bck_kura.png
		
		{ x = 769, y = 199, width = 526, height = 170 }, -- bck_logo.png
		
		{ x = 1228, y = 940, width = 315, height = 379 }, -- bck_stodola.png
		
		{ x = 769, y = 0, width = 768, height = 198 }, -- bck_top.png
		
		{ x = 1517, y = 308, width = 165, height = 187 }, -- bck_zwrotnica.png
		
		{ x = 1849, y = 156, width = 80, height = 80 }, -- button_back.png
		
		{ x = 1228, y = 1321, width = 98, height = 98 }, -- button_i.png
		
		{ x = 1864, y = 238, width = 120, height = 64 }, -- button_ok.png
		
		{ x = 1805, y = 0, width = 226, height = 112 }, -- button_play.png
		
		{ x = 1327, y = 1399, width = 98, height = 98 }, -- button_sound_off.png
		
		{ x = 1946, y = 113, width = 98, height = 98 }, -- button_sound_on.png
		
		{ x = 873, y = 1429, width = 80, height = 80 }, -- constructor.png
		
		{ x = 0, y = 1364, width = 768, height = 667 }, -- credits_bck.png
		
		{ x = 1517, y = 199, width = 18, height = 18 }, -- dot_page.png
		
		{ x = 1931, y = 212, width = 24, height = 24 }, -- dot_page_current.png
		
		{ x = 1392, y = 511, width = 103, height = 77 }, -- kura_oczy_00.png
		
		{ x = 1327, y = 1321, width = 103, height = 77 }, -- kura_oczy_01.png
		
		{ x = 769, y = 1429, width = 103, height = 77 }, -- kura_oczy_02.png
		
		{ x = 1290, y = 445, width = 212, height = 65 }, -- label_extras.png
		
		{ x = 1517, y = 238, width = 346, height = 69 }, -- label_selectbox.png
		
		{ x = 1887, y = 113, width = 28, height = 36 }, -- level1.png
		
		{ x = 875, y = 1510, width = 28, height = 36 }, -- level10.png
		
		{ x = 984, y = 1466, width = 28, height = 36 }, -- level11.png
		
		{ x = 1451, y = 589, width = 28, height = 36 }, -- level12.png
		
		{ x = 1916, y = 113, width = 28, height = 36 }, -- level13.png
		
		{ x = 1435, y = 889, width = 28, height = 36 }, -- level14.png
		
		{ x = 1392, y = 589, width = 28, height = 36 }, -- level15.png
		
		{ x = 1131, y = 1429, width = 28, height = 36 }, -- level16.png
		
		{ x = 1287, y = 889, width = 28, height = 36 }, -- level17.png
		
		{ x = 1510, y = 885, width = 28, height = 36 }, -- level18.png
		
		{ x = 1611, y = 496, width = 28, height = 36 }, -- level19.png
		
		{ x = 1043, y = 1429, width = 28, height = 36 }, -- level2.png
		
		{ x = 1258, y = 889, width = 28, height = 36 }, -- level20.png
		
		{ x = 1072, y = 1466, width = 28, height = 36 }, -- level21.png
		
		{ x = 1421, y = 589, width = 28, height = 36 }, -- level22.png
		
		{ x = 1317, y = 889, width = 28, height = 36 }, -- level23.png
		
		{ x = 1376, y = 889, width = 28, height = 36 }, -- level24.png
		
		{ x = 1405, y = 889, width = 28, height = 36 }, -- level25.png
		
		{ x = 1641, y = 571, width = 28, height = 36 }, -- level26.png
		
		{ x = 1346, y = 889, width = 28, height = 36 }, -- level27.png
		
		{ x = 1102, y = 1466, width = 28, height = 36 }, -- level28.png
		
		{ x = 1611, y = 571, width = 28, height = 36 }, -- level29.png
		
		{ x = 1013, y = 1429, width = 28, height = 36 }, -- level3.png
		
		{ x = 1729, y = 603, width = 28, height = 36 }, -- level30.png
		
		{ x = 1161, y = 1466, width = 28, height = 36 }, -- level31.png
		
		{ x = 1611, y = 533, width = 28, height = 36 }, -- level32.png
		
		{ x = 984, y = 1429, width = 28, height = 36 }, -- level33.png
		
		{ x = 1220, y = 1466, width = 28, height = 36 }, -- level34.png
		
		{ x = 1641, y = 533, width = 28, height = 36 }, -- level35.png
		
		{ x = 1102, y = 1429, width = 28, height = 36 }, -- level36.png
		
		{ x = 1464, y = 889, width = 28, height = 36 }, -- level37.png
		
		{ x = 1190, y = 1466, width = 28, height = 36 }, -- level38.png
		
		{ x = 1700, y = 603, width = 28, height = 36 }, -- level39.png
		
		{ x = 904, y = 1510, width = 28, height = 36 }, -- level4.png
		
		{ x = 1220, y = 1429, width = 28, height = 36 }, -- level40.png
		
		{ x = 954, y = 1429, width = 28, height = 36 }, -- level41.png
		
		{ x = 1670, y = 603, width = 28, height = 36 }, -- level42.png
		
		{ x = 1540, y = 885, width = 28, height = 36 }, -- level43.png
		
		{ x = 1161, y = 1429, width = 28, height = 36 }, -- level44.png
		
		{ x = 1043, y = 1466, width = 28, height = 36 }, -- level45.png
		
		{ x = 1249, y = 1457, width = 28, height = 36 }, -- level46.png
		
		{ x = 954, y = 1466, width = 28, height = 36 }, -- level47.png
		
		{ x = 1013, y = 1466, width = 28, height = 36 }, -- level48.png
		
		{ x = 1190, y = 1429, width = 28, height = 36 }, -- level49.png
		
		{ x = 845, y = 1510, width = 28, height = 36 }, -- level5.png
		
		{ x = 1641, y = 496, width = 28, height = 36 }, -- level50.png
		
		{ x = 1249, y = 1495, width = 28, height = 36 }, -- level6.png
		
		{ x = 1072, y = 1429, width = 28, height = 36 }, -- level7.png
		
		{ x = 1131, y = 1466, width = 28, height = 36 }, -- level8.png
		
		{ x = 1249, y = 1420, width = 28, height = 36 }, -- level9.png
		
		{ x = 1290, y = 511, width = 101, height = 125 }, -- level_border.png
		
		{ x = 1503, y = 496, width = 107, height = 132 }, -- level_egg_empty.png
		
		{ x = 1759, y = 603, width = 89, height = 115 }, -- level_egg_full.png
		
		{ x = 1805, y = 113, width = 43, height = 42 }, -- level_star1.png
		
		{ x = 1290, y = 370, width = 4, height = 61 }, -- separator_dots.png
		
		{ x = 769, y = 1507, width = 75, height = 74 }, -- star_shadow.png
		
		{ x = 769, y = 643, width = 488, height = 296 }, -- world_1.png
		
		{ x = 1538, y = 160, width = 310, height = 69 }, -- world_1_txt.png
		
		{ x = 769, y = 370, width = 520, height = 272 }, -- world_2.png
		
		{ x = 1258, y = 643, width = 487, height = 100 }, -- world_shadow.png
		
		{ x = 1517, y = 218, width = 17, height = 18 }, -- x.png
		
		{ x = 1849, y = 113, width = 37, height = 42 }, -- yolk.png
		
	},

	sheetContentWidth = 2048,
	sheetContentHeight = 2048,

	frameIndex =
	{
		
		["bck.png"] = 1,
		
		["bck_chmura_01.png"] = 2,
		
		["bck_chmura_02.png"] = 3,
		
		["bck_chmura_03.png"] = 4,
		
		["bck_chmura_04.png"] = 5,
		
		["bck_jajo.png"] = 6,
		
		["bck_kamienie.png"] = 7,
		
		["bck_kura.png"] = 8,
		
		["bck_logo.png"] = 9,
		
		["bck_stodola.png"] = 10,
		
		["bck_top.png"] = 11,
		
		["bck_zwrotnica.png"] = 12,
		
		["button_back.png"] = 13,
		
		["button_i.png"] = 14,
		
		["button_ok.png"] = 15,
		
		["button_play.png"] = 16,
		
		["button_sound_off.png"] = 17,
		
		["button_sound_on.png"] = 18,
		
		["constructor.png"] = 19,
		
		["credits_bck.png"] = 20,
		
		["dot_page.png"] = 21,
		
		["dot_page_current.png"] = 22,
		
		["kura_oczy_00.png"] = 23,
		
		["kura_oczy_01.png"] = 24,
		
		["kura_oczy_02.png"] = 25,
		
		["label_extras.png"] = 26,
		
		["label_selectbox.png"] = 27,
		
		["level1.png"] = 28,
		
		["level10.png"] = 29,
		
		["level11.png"] = 30,
		
		["level12.png"] = 31,
		
		["level13.png"] = 32,
		
		["level14.png"] = 33,
		
		["level15.png"] = 34,
		
		["level16.png"] = 35,
		
		["level17.png"] = 36,
		
		["level18.png"] = 37,
		
		["level19.png"] = 38,
		
		["level2.png"] = 39,
		
		["level20.png"] = 40,
		
		["level21.png"] = 41,
		
		["level22.png"] = 42,
		
		["level23.png"] = 43,
		
		["level24.png"] = 44,
		
		["level25.png"] = 45,
		
		["level26.png"] = 46,
		
		["level27.png"] = 47,
		
		["level28.png"] = 48,
		
		["level29.png"] = 49,
		
		["level3.png"] = 50,
		
		["level30.png"] = 51,
		
		["level31.png"] = 52,
		
		["level32.png"] = 53,
		
		["level33.png"] = 54,
		
		["level34.png"] = 55,
		
		["level35.png"] = 56,
		
		["level36.png"] = 57,
		
		["level37.png"] = 58,
		
		["level38.png"] = 59,
		
		["level39.png"] = 60,
		
		["level4.png"] = 61,
		
		["level40.png"] = 62,
		
		["level41.png"] = 63,
		
		["level42.png"] = 64,
		
		["level43.png"] = 65,
		
		["level44.png"] = 66,
		
		["level45.png"] = 67,
		
		["level46.png"] = 68,
		
		["level47.png"] = 69,
		
		["level48.png"] = 70,
		
		["level49.png"] = 71,
		
		["level5.png"] = 72,
		
		["level50.png"] = 73,
		
		["level6.png"] = 74,
		
		["level7.png"] = 75,
		
		["level8.png"] = 76,
		
		["level9.png"] = 77,
		
		["level_border.png"] = 78,
		
		["level_egg_empty.png"] = 79,
		
		["level_egg_full.png"] = 80,
		
		["level_star1.png"] = 81,
		
		["separator_dots.png"] = 82,
		
		["star_shadow.png"] = 83,
		
		["world_1.png"] = 84,
		
		["world_1_txt.png"] = 85,
		
		["world_2.png"] = 86,
		
		["world_shadow.png"] = 87,
		
		["x.png"] = 88,
		
		["yolk.png"] = 89,
		
	}
}

return sheet